baseURL = "https://shreve.io"
languageCode = "en-us"
enableRobotsTXT = true
enableGitInfo = true
# disableKinds = ["taxonomies", "categories"]
title = "Shreve Labs"
pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"
series = "series"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[imaging]
hint = "picture"
quality = 100
resampleFilter = "lanczos"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
